const fs = require('fs');
let css = fs.readFileSync('pages/public/landing/landing.css', 'utf8');

const replacements = [
    ["/* GSAP Safety Fallback — content always visible before GSAP initializes. */", "/* GSAP Safety Fallback — Đảm bảo nội dung luôn hiển thị trước khi GSAP khởi tạo */"],
    ["/* Single eyebrow — used once on the whole page */", "/* Eyebrow - Chỉ dùng một lần trên toàn bộ trang */"],
    ["/* Reduced slightly to ensure it fits perfectly on exactly 2 lines */", "/* Giảm một chút để vừa vặn trên đúng 2 dòng */"],
    ["/* Actions row: CTA + social proof side-by-side */", "/* Dòng hành động: CTA + Bằng chứng xã hội (Social Proof) nằm ngang */"],
    ["/* Social proof — compact, sits next to CTA */", "/* Bằng chứng xã hội — thu gọn, nằm cạnh CTA */"],
    ["/* Bottom row: social proof + separator + status widget side by side */", "/* Dòng cuối: Bằng chứng xã hội + Đường phân cách + Widget trạng thái */"],
    ["/* Photo frame with floating badges */", "/* Khung ảnh kèm huy hiệu nổi */"],
    ["/* badges can overflow */", "/* Cho phép huy hiệu tràn viền */"],
    ["/* Floating metric badges on the photo */", "/* Huy hiệu thông số nổi trên ảnh */"],
    ["/* Real-time tracker pill on photo */", "/* Thẻ theo dõi trạng thái thời gian thực trên ảnh */"],
    ["/* Hide floating badges on subsequent slides to avoid overlap with caption cards */", "/* Ẩn huy hiệu nổi trên các slide tiếp theo để tránh trùng lặp */"],
    ["/* Row 1: 2 featured cards bằng nhau */", "/* Hàng 1: 2 thẻ nổi bật bằng nhau */"],
    ["/* Row 2: 3 cards equal width */", "/* Hàng 2: 3 thẻ độ rộng bằng nhau */"],
    ["/* Featured card fills full height of row-top */", "/* Thẻ nổi bật lấp đầy chiều cao của phần trên */"],
    ["/* Stack container - 2 mini cards bên phải, chiều cao bằng featured */", "/* Cột stack - chứa 2 thẻ mini bên phải, cao bằng thẻ nổi bật */"],
    ["/* Featured card image */", "/* Ảnh thẻ nổi bật */"],
    ["/* Mini card image — short */", "/* Ảnh thẻ mini — thấp */"],
    ["/* Wide card image */", "/* Ảnh thẻ rộng */"],
    ["/* Featured CTA button — more prominent */", "/* Nút CTA nổi bật — thu hút sự chú ý hơn */"],
    ["/* Badge — positioned on image */", "/* Huy hiệu — đặt trên ảnh */"],
    ["/* Active/selected mini card */", "/* Thẻ mini đang được chọn/hoạt động */"],
    ["/* Row 1: 2 featured → 1 cột */", "/* Hàng 1: 2 thẻ nổi bật → 1 cột */"],
    ["/* Row 2: 3 → 2 cột */", "/* Hàng 2: 3 thẻ → 2 cột */"],
    ["/* Row 2: single column trên mobile nhỏ */", "/* Hàng 2: 1 cột trên thiết bị di động nhỏ */"],
    ["/* Legacy arched-card classes kept so other pages don't break */", "/* Giữ lại class của arched-card cũ để không làm hỏng các trang khác */"],
    ["/* Col 1: landscape ngang */", "/* Cột 1: ảnh ngang */"],
    ["/* Col 2: vuông */", "/* Cột 2: ảnh vuông */"],
    ["/* Col 3: cùng tầm với col 1 */", "/* Cột 3: cùng độ cao với cột 1 */"],
    ["/* 4-column grid, căn giữa */", "/* Lưới 4 cột, căn giữa */"],
    ["/* Connecting line chạy qua giữa các dots */", "/* Đường nối chạy ngang qua giữa các điểm (dots) */"],
    ["/* dưới ảnh + giữa dot */", "/* dưới ảnh + giữa điểm */"],
    ["/* Compact above banner */", "/* Thu gọn trên banner */"],
    ["/* Slimmer fixed height on desktop */", "/* Chiều cao cố định, thon gọn hơn trên desktop */"],
    ["/* Reduced padding for compact layout */", "/* Giảm khoảng cách cho bố cục gọn gàng */"],
    ["/* Slightly smaller heading size */", "/* Kích thước tiêu đề nhỏ hơn một chút */"],
    ["/* Scaled down copy text */", "/* Chữ thu nhỏ lại */"],
    ["/* Reduced gap */", "/* Giảm khoảng trống */"],
    ["/* Smaller button */", "/* Nút nhỏ hơn */"],
    ["/* Let stack naturally on tablet/mobile */", "/* Xếp chồng tự nhiên trên tablet/mobile */"],
    ["/* 3 cards × 320px + gaps */", "/* 3 thẻ × 320px + khoảng trống */"],
    ["/* Active / Hover card elevations and border colors */", "/* Độ nổi và viền khi hover / active thẻ */"],
    ["/* Phone Mockup Frame */", "/* Khung giả lập điện thoại (Mockup) */"],
    ["/* Phone camera notch notch */", "/* Rãnh (notch) camera trên điện thoại */"],
    ["/* Hide scrollbar */", "/* Ẩn thanh cuộn */"],
    ["/* ensure relative positioning for live camera tag overlay */", "/* Đảm bảo vị trí relative để hiển thị tag camera trực tiếp (overlay) */"],
    ["/* Live Camera Tag in mockups */", "/* Tag Camera Trực tiếp trong mockup */"],
    ["/* Deep green translucent */", "/* Xanh lá đậm trong suốt */"],
    ["/* bright red */", "/* Đỏ tươi */"],
    ["/* Pet ID Registration note */", "/* Ghi chú đăng ký Pet ID */"],
    ["/* Force single line on desktop */", "/* Bắt buộc hiển thị một dòng trên desktop */"],
    ["/* Reduced space below subtitle */", "/* Giảm khoảng cách dưới phụ đề */"],
    ["/* Prevent subtitle wrapping on desktop */", "/* Ngăn phụ đề rớt dòng trên desktop */"],
    ["/* Steps Flow (Restored to original pill styling, width optimized) */", "/* Luồng các bước (Khôi phục style nguyên bản dạng pill, tối ưu chiều rộng) */"],
    ["/* Balanced left-right padding */", "/* Cân bằng padding trái phải */"],
    ["/* Wrap tightly around content instead of static wide layout */", "/* Ôm sát nội dung thay vì dùng chiều rộng cố định */"],
    ["/* Increased bottom spacing to cards */", "/* Tăng khoảng cách ở dưới tới các thẻ */"],
    ["/* Prevent step labels from wrapping internally */", "/* Ngăn chữ trong các nhãn bước rớt dòng */"],
    ["/* Interactive Card Showcase Layout */", "/* Bố cục hiển thị thẻ tương tác (Interactive Card) */"],
    ["/* Left Column: Wallet Pass Visual */", "/* Cột trái: Hình ảnh Thẻ Wallet */"],
    ["/* Slightly wider ratio to reduce height */", "/* Tỉ lệ rộng hơn một chút để giảm chiều cao */"],
    ["/* Virtual Card Elements */", "/* Các thành phần của Thẻ ảo */"],
    ["/* Three Tier Card layout on the right */", "/* Bố cục 3 hạng thẻ (Tier) bên phải */"],
    ["/* Specific Tiers Hover Borders & Shadows */", "/* Viền và Bóng mờ khi hover vào từng hạng thẻ cụ thể */"],
    ["/* Dim down other cards when one card is hovered */", "/* Làm mờ các thẻ khác khi hover vào một thẻ */"],
    ["/* Bottom CTA section */", "/* Khu vực CTA phía dưới */"],
    ["/* Responsive adjustment for Membership split layout */", "/* Tinh chỉnh responsive cho bố cục Membership */"],
    ["/* Mobile drawer header rules moved to shared style.css (.nav-menu drawer @ 991.98px) */", "/* Style header mobile drawer đã chuyển sang style.css dùng chung */"],
    ["/* Safety & Commitment Section */", "/* Phần An toàn & Cam kết */"],
    ["/* Statement block */", "/* Khối tuyên bố (Statement) */"],
    ["/* Divider */", "/* Dòng phân cách (Divider) */"],
    ["/* Stats row */", "/* Dòng chỉ số (Stats) */"],
    ["/* Shop Features Inline Bar (Compact inline badges replacing subtitle) */", "/* Thanh tính năng Cửa hàng (Huy hiệu thu gọn thay thế phụ đề) */"],
    ["/* Fix: booking/pricing modal không được chiếm không gian layout */", "/* Sửa lỗi: modal đặt lịch/bảng giá không chiếm không gian bố cục */"],
    ["/* Landing shop cards: wishlist sits on image top-right like service cards */", "/* Các thẻ sản phẩm landing: nút tim đặt góc trên bên phải giống thẻ dịch vụ */"]
];

replacements.forEach(([search, replace]) => {
    css = css.split(search).join(replace);
});

fs.writeFileSync('pages/public/landing/landing.css', css, 'utf8');
