-- ==========================================
-- BẢNG 7: service
-- ==========================================
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000001', 'SPA01', 'Gói Tắm Vệ Sinh Cơ Bản', 'GROOMING_SPA', 'Liệu trình tắm làm sạch và khử mùi hôi cơ bản dành cho các bé chó mèo có sức khỏe da lông bình thường, giúp duy trì vệ sinh sạch sẽ định kỳ hàng tuần.', 60, 'assets/images/services/spa/process/spa01.webp', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000002', 'SPA02', 'Gói Tắm Dưỡng Premium', 'GROOMING_SPA', 'Liệu trình tắm dưỡng chuyên sâu kết hợp massage thư giãn, phục hồi lông hư tổn, giảm rối lông và nuôi dưỡng làn da nhạy cảm bằng các dòng mỹ phẩm cao cấp.', 90, 'assets/images/services/spa/process/tam_cho5.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000003', 'SPA03', 'Gói Spa Khử Mùi Chuyên Sâu', 'GROOMING_SPA', 'Giải pháp spa đặc trị mùi hôi cơ thể cứng đầu dành cho các giống chó năng động, vận động ngoài trời nhiều hoặc có tuyến bã nhờn hoạt động mạnh.', 120, 'assets/images/services/spa/process/tam_cho1.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000004', 'SPA04', 'Express Care – Vệ Sinh Nhanh', 'GROOMING_SPA', 'Dịch vụ chăm sóc nhanh tại quầy giúp làm sạch bụi bẩn bên ngoài và khử mùi khẩn cấp cho chó mèo trước khi về nhà hoặc khi chủ nuôi có lịch trình bận rộn.', 30, 'assets/images/services/spa/process/rua_chan.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000005', 'SPA05', 'Cắt Móng & Vệ Sinh Tai', 'GROOMING_SPA', 'Chăm sóc cục bộ định kỳ hai tuần một lần giúp bảo vệ bàn chân và tai của thú cưng luôn trong tình trạng sạch sẽ, thoải mái nhất.', 20, 'assets/images/services/spa/process/cat_mong.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000006', 'SPA06', 'Tắm Khô Khử Mùi', 'GROOMING_SPA', 'Giải pháp làm sạch lông da bằng bọt tắm khô chuyên dụng không cần dùng nước, cực kỳ phù hợp cho các bé đang ốm, sau tiêm phòng hoặc sợ nước.', 35, 'assets/images/services/spa/process/VS-XIT-07_2.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000007', 'SPA07', 'Grooming Tạo Kiểu Cơ Bản', 'GROOMING_SPA', 'Gói làm đẹp toàn diện bao gồm tắm vệ sinh kỹ lưỡng kết hợp cắt tỉa lông tạo kiểu cơ bản (như cắt tròn mặt Boo, tỉa gọn chân) theo tiêu chuẩn giống loài.', 150, 'assets/images/services/spa/process/cat_long1.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000008', 'SPA08', 'Grooming Theo Yêu Cầu', 'GROOMING_SPA', 'Dịch vụ tạo mẫu tóc cao cấp thiết kế kiểu dáng lông theo hình ảnh mẫu yêu cầu riêng của chủ nuôi hoặc tạo kiểu nghệ thuật phức tạp cho bé đi thi show.', 180, 'assets/images/services/spa/process/cao_long.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000009', 'SPA09', 'Cat Grooming Chuyên Biệt', 'GROOMING_SPA', 'Liệu trình chăm sóc và cắt tỉa làm đẹp dành riêng cho loài mèo nhạy cảm, dễ bị kích động, sử dụng các kỹ thuật xoa dịu đặc biệt không gây áp lực.', 120, 'assets/images/services/spa/process/tam_meo.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000010', 'SPA10', 'Tắm Thuốc Trị Liệu Da Liễu', 'GROOMING_SPA', 'Dịch vụ tắm trị liệu viêm da, nấm, ghẻ, ký sinh trùng bằng các loại dầu tắm y khoa và lá thuốc thảo mộc đông y cô đặc, hỗ trợ hồi phục da tổn thương.', 90, 'assets/images/services/spa/process/tam_cho4.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000011', 'SPA11', 'Nhuộm Lông Nghệ Thuật An Toàn', 'GROOMING_SPA', 'Thiết kế nhuộm màu thời trang cho một số phân vùng lông như tai, đuôi, chân bằng màu nhuộm thảo dược chiết xuất tự nhiên 100% không gây kích ứng da.', 90, 'assets/images/services/spa/process/spa11.webp', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000012', 'SPA12', 'Gói Paw Care Premium – Chăm Sóc Bàn Chân', 'GROOMING_SPA', 'Liệu trình chăm sóc chuyên biệt cho bốn bàn chân, cắt tỉa gọn gàng lông kẽ chân, vệ sinh móng và thoa kem dưỡng ẩm đệm chân cao cấp.', 45, 'assets/images/services/spa/process/rua_chan.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000013', 'SPA13', 'Gói Tắm & Sấy Vệ Sinh Thú Nhỏ', 'GROOMING_SPA', 'Liệu trình làm sạch lông da đặc biệt nhẹ nhàng dành riêng cho thỏ cảnh, bọ ú (guinea pig) vốn là những loài dễ bị hạ thân nhiệt và stress nặng khi gặp nước.', 60, 'assets/images/services/spa/process/spa01.webp', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000014', 'SPA14', 'Vệ Sinh Răng & Cắt Móng Thú Nhỏ', 'GROOMING_SPA', 'Dịch vụ vệ sinh cục bộ định kỳ, hỗ trợ cắt tỉa móng chân dài sắc nhọn và kiểm tra, mài dũa móng hoặc răng cửa bị mọc quá dài cho thỏ, hamster, bọ ú.', 25, 'assets/images/services/spa/process/cat_mong.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000015', 'HTL01', 'Phòng Standard', 'GROOMING_SPA', 'Không gian phòng lưu trú cơ bản tiêu chuẩn sạch sẽ, thoáng mát, thích hợp cho các bé chó mèo nhỏ hướng nội, thích sự yên tĩnh khi vắng chủ.', 60, 'assets/images/services/hotel/htl01.webp', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000016', 'HTL02', 'Phòng Standard Plus', 'GROOMING_SPA', 'Không gian phòng rộng rãi hơn thích hợp cho chó mèo size vừa hoặc hai bé cún nhỏ cùng một nhà lưu trú chung để bầu bạn cùng nhau.', 60, 'assets/images/services/hotel/htl02.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000017', 'HTL03', 'Phòng Deluxe', 'PET_TAXI', 'Hạng phòng lưu trú cao cấp được trang bị Camera IP giám sát 24/7 riêng cho từng phòng giúp chủ nuôi tự theo dõi hình ảnh bé trực tiếp từ xa qua website.', 60, 'assets/images/services/hotel/htl03.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000018', 'HTL04', 'Phòng Cat Condo – Khách Sạn Cho Mèo', 'PET_HOTEL', 'Hạng phòng được thiết kế cấu trúc chiều dọc chuyên biệt cho loài mèo với các bậc leo trèo nhảy nhót, trụ cào móng và võng nằm êm ái thư giãn.', 60, 'assets/images/services/hotel/htl04.jfif', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000019', 'HTL05', 'Luxury Suite', 'PET_HOTEL', 'Biệt thự lưu trú hoàng gia siêu rộng rãi được thiết kế như một căn hộ nhỏ ấm cúng dành cho thú cưng VIP, có khu vui chơi riêng và chế độ chăm sóc 1:1.', 60, 'assets/images/services/hotel/htl05.webp', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000020', 'HTL06', 'Presidential Pet Suite', 'PET_HOTEL', 'Hạng phòng Presidential cao cấp nhất dành riêng cho các bé chó giống lớn (>20kg) như Golden Retriever, Husky, Alaska. Chăm sóc bởi Chuyên gia 1:1.', 60, 'assets/images/services/hotel/htl06.jpg', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000021', 'HTL07', 'Dịch Vụ Bán Trú Trong Ngày (Daycare)', 'PET_HOTEL', 'Giải pháp gửi giữ thú cưng theo giờ hoặc trong ngày dành cho chủ nuôi bận rộn đi làm, đi công tác ngắn giờ, đảm bảo bé có bạn chơi đùa dưới sự giám sát.', 60, 'assets/images/services/hotel/htl07.jfif', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000022', 'HTL08', 'Phòng Small Pet Condo – Khách Sạn Thú Nhỏ', 'PET_HOTEL', 'Hạng phòng gỗ chuyên dụng, an toàn cách âm tốt dành riêng cho các loài thú cưng nhỏ như Thỏ, Hamster, Bọ ú, được trang bị đầy đủ mùn cưa lót chuồng organic và đồ chơi.', 60, 'assets/images/services/hotel/htl08.jfif', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.service (id, service_code, service_name, service_category, description, estimated_duration, thumbnail_url, status, created_at, updated_at) VALUES ('c0000000-0000-0000-0000-000000000023', 'TXI01', 'Dịch Vụ Xe Đưa Đón Tận Nơi (Pet Taxi)', 'PET_TAXI', 'Dịch vụ đưa đón thú cưng an toàn tận nhà bằng xe ô tô chuyên dụng có lồng vận chuyển sạch sẽ cách âm, điều hòa mát mẻ mát mẻ cho bé đi spa/hotel.', 60, 'assets/images/services/txi01.webp', 'ACTIVE', now(), now()) ON CONFLICT (id) DO NOTHING;