-- Đảm bảo Enum có đầy đủ các trạng thái
ALTER TYPE order_status_enum ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE order_status_enum ADD VALUE IF NOT EXISTS 'SHIPPED';
ALTER TYPE order_status_enum ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE order_status_enum ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE order_status_enum ADD VALUE IF NOT EXISTS 'PENDING';

ALTER TYPE appointment_status_enum ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE appointment_status_enum ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TYPE appointment_status_enum ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE appointment_status_enum ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE appointment_status_enum ADD VALUE IF NOT EXISTS 'CANCELLED';

